### ISSUE TITLE
python train_gaussian.py -s ./tandt_db/tandt/train -m ./outputs/train --eval goes wrong

### ISSUE THREAD

**Issue by chensiyuan030105** [ajhamdi/ges-splatting#1]
<img width="681" alt="image" src="https://github.com/ajhamdi/ges-splatting/assets/93069822/49d1722f-6d27-409b-b236-38459aba6d02">

**Comment by zixinzhang02** [comment]
@wunianguiguolu '|' was added in python 3.10, probably you need to upgrade ur python version?

**Comment by zixinzhang02** [comment]
@wunianguiguolu `|` was added in python 3.10, the code runs well in my python 3.10 enviornment.
Probably you need to upgrade your python version to python 3.10.
Or you can try `from __future__ import annotations`.

**Comment by zixinzhang02** [comment]
@wunianguiguolu `|` was added in python 3.10, the code runs well in my python 3.10 environment.
Probably you need to upgrade your python version to python 3.10.
Or you can try `from __future__ import annotations`.

**Comment by ajhamdi** [comment]
fixed now , should work with old python 3.7 environments of the original Gaussian Splatting
