### ISSUE TITLE
Code differences in CUDA

### ISSUE THREAD

**Issue by Vgr20** [ajhamdi/ges-splatting#10]
Hi @ajhamdi! Thanks so much for all the great work you're doing. I noticed that you mentioned updating the CUDA code to support the Beta and Shape Strength parameters, which sounds awesome! However, I couldn't find those changes in the repo—it still seems to be the same as in the original Gaussian Splatting paper. Could you let me know if those updates have been added to the repository yet? Thanks again!

**Comment by ajhamdi** [comment]
hi , sorry for confusion, yes they were originally modified to include the beta and shape strength parameters, but in the latest version, they are actually reverted back to the original CUDA code. The modifications are currently only on the Python renderer not the CUDA code.
