### ISSUE TITLE
How to reproduce figure 9

### ISSUE THREAD

**Issue by MrNeRF** [ajhamdi/ges-splatting#2]
Thank you for this awesome work.
I am interested in reproducing figure 9 where you constrain ges to about the same number of splats as the reference implementation. How to constraint the training to reproduce the results?

Thx and best,
Janusch

**Comment by ajhamdi** [comment]
hey , to do that you have to play with the hyperparameters of Gaussians to make it have fewer components , basically you set the `densify_grad_threshold` = 0.0004
