### ISSUE TITLE
 from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by DiamondGlassDrill** [ajhamdi/ges-splatting#4]
from scene.gaussian_model import GaussianModel
...\ges-splatting\scene\__init__.py", line 20
    from __future__ import annotations
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file

Currently when running either GES or GS i receive this issue

**Comment by ajhamdi** [comment]
fixed now
