### ISSUE TITLE
render() in eval

### ISSUE THREAD

**Issue by chensiyuan030105** [ajhamdi/ges-splatting#5]
In render.py, why do you use original render function instead of render_laplacian? Although you save ply.file as get._scaling() * get.shape(). but it is different from render_laplacian?

**Comment by chensiyuan030105** [comment]
<img width="348" alt="image" src="https://github.com/ajhamdi/ges-splatting/assets/93069822/7d76bdfa-401f-43cc-9626-8ab556dcfbc5">
<img width="364" alt="image" src="https://github.com/ajhamdi/ges-splatting/assets/93069822/8277c297-fdf1-47db-9477-6e6917a90ee5">
<img width="462" alt="image" src="https://github.com/ajhamdi/ges-splatting/assets/93069822/38641317-dd18-489d-9111-845e3b2f32fe">

**Comment by ajhamdi** [comment]
it does not matter because once you initlize the Laplacian components, it assumes the shape_scale is = 1 , so eventually the effect will be the same no matter where you start ( from scratch or from a .ply file )
