### ISSUE TITLE
GES & GS rasterization code difference & debug 

### ISSUE THREAD

**Issue by wuyingxiong** [ajhamdi/ges-splatting#8]
Dear author！
   Thanks for your work!
    I have some questions about the differences in the code between these two models.
    1.Are the cuda parts of these two models, namely diff-gaussian-rasterization and simple-knn, the same?
    2.GES has an additional _shape parameter compared to GS, mainly by changing the size of the scales input into the rasterization. If I want the β value of the GEFs in GES to be as large as possible, which hyperparameter should I adjust?

**Comment by yihua7** [comment]
Same here. I am also wondering what's the difference between GES and GS in the code implementation except for the loss.

**Comment by ajhamdi** [comment]
1- the `diff-gaussian-rasterization` is modified from the original code to allow for the new shape parameter $\beta$. However the new modified rasterizer still allows running the original Gaussian by fixing $\beta=2$ 
2- $\beta$ is learned and can not be set to a specific value , if you need to fix it to a specific value you need to remove the gradients and change its initialization to your desired high value.

**Comment by reachomk** [comment]
Hi, where are these changes made? I ran a diffchecker on forward.cu and backward.cu from submodules/diff-gaussian-rasterization in both ges-splatting and the standard repo, and I cannot seem to find any differences.

**Comment by deepgoyal19** [comment]
I noticed the same thing, @reachomk. The submodule diff-gaussian-rasterization is identical to the original and shows no differences.

**Comment by ajhamdi** [comment]
hi , sorry for the confusion, yes they were originally modified to include the beta and shape strength parameters, but in the latest version, they are actually reverted back to the original `forward.cu` CUDA code. The modifications are currently only on the Python renderer not the CUDA code.
